# FROM louislam/uptime-kuma:base-debian AS build

# DON'T UPDATE TO node:14-bullseye-slim, see #372.
# If the image changed, the second stage image should be changed too
FROM node:16-buster-slim as build
ARG TARGETPLATFORM

WORKDIR /app

# Install Curl
# Install Apprise, add sqlite3 cli for debugging in the future, iputils-ping for ping, util-linux for setpriv
# Stupid python3 and python3-pip actually install a lot of useless things into Debian, specify --no-install-recommends to skip them, make the base even smaller than alpine!

RUN apt update && apt upgrade -y && \
    apt --yes --no-install-recommends install wget ca-certificates build-essential libncursesw5-dev libssl-dev \
        libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev && \
    wget https://www.python.org/ftp/python/3.10.5/Python-3.10.5.tgz && tar xzf Python-3.10.5.tgz && \
    cd Python-3.10.5 && ./configure --enable-optimizations  && make && make install && \
    apt --yes --no-install-recommends install python3-pip python3-cryptography python3-six python3-yaml python3-click python3-markdown python3-requests python3-requests-oauthlib \
        sqlite3 iputils-ping util-linux dumb-init && \
    pip3 --no-cache-dir install pip3 apprise==0.9.8.3 && \
    apt --yes remove wget build-essential libncursesw5-dev libssl-dev \
        libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev && \
    rm -rf /var/lib/apt/lists/*

# Install cloudflared
# dpkg --add-architecture arm: cloudflared do not provide armhf, this is workaround. Read more: https://github.com/cloudflare/cloudflared/issues/583
COPY extra/download-cloudflared.js ./extra/download-cloudflared.js
RUN node ./extra/download-cloudflared.js $TARGETPLATFORM && \
    dpkg --add-architecture arm && \
    apt update && \
    apt --yes --no-install-recommends install ./cloudflared.deb && \
    rm -rf /var/lib/apt/lists/* && \
    rm -f cloudflared.deb


ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1

COPY . .

RUN npm ci --omit=dev && \
    chmod +x /app/extra/entrypoint.sh


FROM build

WORKDIR /app

# Copy app files from build layer
COPY --from=build /app /app
RUN pip3 install --no-cache-dir -r requirements.txt && \
    chmod +x /app/start.sh

EXPOSE 3001
VOLUME ["/app/data"]
HEALTHCHECK --interval=60s --timeout=30s --start-period=180s --retries=5 CMD node extra/healthcheck.js
ENTRYPOINT ["/usr/bin/dumb-init", "--", "extra/entrypoint.sh"]
# CMD ["node", "server/server.js"]
CMD ["bash", "start.sh"]

